"""initial schema

Revision ID: 7dbfbb552bbd
Revises:
Create Date: 2026-07-01 18:35:51.440104

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7dbfbb552bbd"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "problems",
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column(
            "difficulty",
            sa.Enum("easy", "medium", "hard", name="difficulty"),
            nullable=False,
        ),
        sa.Column("track", sa.Enum("algo", "sql", name="track"), nullable=False),
        sa.Column("pattern", sa.String(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("added_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("slug"),
    )
    op.create_index(
        "ix_problems_track_order_index", "problems", ["track", "order_index"]
    )
    op.create_table(
        "progress",
        sa.Column("problem_slug", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("introduced", "learning", "maintenance", name="status"),
            nullable=False,
        ),
        sa.Column("introduced_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("interval_index", sa.Integer(), nullable=True),
        sa.Column("last_reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_review_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["problem_slug"],
            ["problems.slug"],
        ),
        sa.PrimaryKeyConstraint("problem_slug"),
    )
    op.create_index("ix_progress_status", "progress", ["status"])
    op.create_index("ix_progress_next_review_at", "progress", ["next_review_at"])
    op.create_table(
        "submissions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("problem_slug", sa.String(), nullable=False),
        sa.Column("solved_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["problem_slug"],
            ["problems.slug"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "problem_slug", "solved_at", name="uq_submission_slug_time"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("submissions")
    op.drop_index("ix_progress_next_review_at", table_name="progress")
    op.drop_index("ix_progress_status", table_name="progress")
    op.drop_table("progress")
    op.drop_index("ix_problems_track_order_index", table_name="problems")
    op.drop_table("problems")
    # ### end Alembic commands ###
